name: Build and Push Package (Prod)

on:
  release:
    types: [ published ]

env:
  ENVIRONMENT: prod
  REPOSITORY_NAME: ${{ github.event.repository.name }}
  IMAGE_REPOSITORY: ${{ vars.REGISTRY }}/${{ vars.ORGANIZATION }}/${{ github.event.repository.name }}
  APP_VERSION: ${{ github.event.release.tag_name }}
  HOST: ${{ vars.HOST }}

jobs:
  build-and-push:
    environment: prod
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: refs/tags/${{ env.APP_VERSION }}

      - name: Build jar with Gradle
        uses: IsItgone/ci-templates/.github/actions/build-jar@main

      - name: Build and Push image with Docker buildx
        uses: IsItgone/ci-templates/.github/actions/build-and-push-image@main
        with:
          registry: ${{ vars.REGISTRY }}
          tags: |
            ${{ env.IMAGE_REPOSITORY }}:${{ env.APP_VERSION }},
            ${{ env.IMAGE_REPOSITORY }}:latest
          password: ${{ secrets.GHCR_TOKEN }}

  update-helm-chart:
    needs: build-and-push
    environment: ${{ env.ENVIRONMENT }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ vars.ORGANIZATION }}/cluster-config
          token: ${{ secrets.GITOPS_TOKEN }}

      - name: Update Helm Chart
        working-directory: apps/${{ env.REPOSITORY_NAME }}/${{ env.ENVIRONMENT }}/chart
        run: |
          yq -i '.version = "${{ env.APP_VERSION }}"' Chart.yaml
          yq -i '.appVersion = "${{ env.APP_VERSION }}"' Chart.yaml
          yq -i '.spring-base.image.repository = "${{ env.IMAGE_REPOSITORY }}"' values.yaml
          yq -i '.spring-base.image.tag = "${{ env.APP_VERSION }}"' values.yaml
          yq -i '.spring-base.ingress.host = "${{ env.HOST }}"' values.yaml

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update Image tag to ${{ env.APP_VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITOPS_TOKEN }}