name: Build and Push Package (Dev)

on:
  push:
    branches:
      - main
      - ci
  workflow_dispatch:

env:
  IMAGE_REPOSITORY: ${{ vars.REGISTRY }}/${{ vars.ORGANIZATION }}/${{ github.event.repository.name }}
  APP_VERSION: ${{ github.sha }}
  HOST: dev.${{ vars.HOST }}

jobs:
  build-and-push:
    environment: dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build jar with Gradle
        uses: IsItgone/ci-templates/.github/actions/build-jar@main

      - name: Build and Push image with Docker buildx
        uses: IsItgone/ci-templates/.github/actions/build-and-push-image@main
        with:
          registry: ${{ vars.REGISTRY }}
          tags: |
            ${{ env.IMAGE_REPOSITORY }}:${{ env.APP_VERSION }}
          password: ${{ secrets.GHCR_TOKEN }}

  update-helm-chart:
    needs: build-and-push
    environment: dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: charts

      - name: Update App version
        uses: mikefarah/yq@v4
        with:
          cmd: |
            '.appVersion = "${{ env.APP_VERSION }}"' Chart.yaml

      - name: Update Image repository
        uses: mikefarah/yq@v4
        with:
          cmd: |
            '.image.repository = "${{ env.IMAGE_REPOSITORY }}"' values.yaml

      - name: Update Host
        uses: mikefarah/yq@v4
        with:
          cmd: |
            '.ingress.host = "${{ env.HOST }}"' dev-values.yaml