name: Build and Push Package (Prod)

on:
  release:
    types: [ published ]

env:
  IMAGE_PREFIX: ${{ vars.REGISTRY }}/${{ vars.ORGANIZATION }}/${{ github.event.repository.name }}
  RELEASE_TAG: ${{ github.event.release.tag_name }}

jobs:
  build-and-push:
    environment: prod
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: refs/tags/${{ env.RELEASE_TAG }}

      - name: Build jar with Gradle
        uses: IsItgone/ci-templates/.github/actions/build-jar@main

      - name: Build and Push image with Docker buildx
        uses: IsItgone/ci-templates/.github/actions/build-and-push-image@main
        with:
          registry: ${{ vars.REGISTRY }}
          tags: |
            ${{ env.IMAGE_PREFIX }}:${{ env.RELEASE_TAG }},
            ${{ env.IMAGE_PREFIX }}:latest
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
