name: Build, Push, Deploy (Dev)

on:
  push:
    branches:
      - main
      - ci
  workflow_dispatch:

env:
  ENVIRONMENT: dev
  REPOSITORY_NAME: ${{ github.event.repository.name }}
  IMAGE_REPOSITORY: ${{ vars.REGISTRY }}/${{ vars.ORGANIZATION }}/${{ github.event.repository.name }}
  APP_VERSION: ${{ github.sha }}
  HOST: dev.${{ vars.HOST }}

jobs:
  build-and-push:
    environment: dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build jar with Gradle
        uses: IsItgone/ci-templates/.github/actions/build-jar@main

      - name: Build and Push image with Docker buildx
        uses: IsItgone/ci-templates/.github/actions/build-and-push-image@main
        with:
          registry: ${{ vars.REGISTRY }}
          tags: |
            ${{ env.IMAGE_REPOSITORY }}:${{ env.APP_VERSION }}
          password: ${{ secrets.GHCR_TOKEN }}

  update-helm-chart:
    needs: build-and-push
    permissions:
      contents: write
    environment: dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ vars.ORGANIZATION }}/cluster-config

      - name: Update Helm Chart
        uses: mikefarah/yq@v4
        working-directory: cluster-config/apps/${{ env.REPOSITORY_NAME }}/${{ env.ENVIRONMENT }}/chart
        with:
          cmd: |
            yq -i '.appVersion = "${{ env.APP_VERSION }}"' Chart.yaml
            yq -i '.spring-base.image.repository = "${{ env.IMAGE_REPOSITORY }}"' values.yaml
            yq -i '.spring-base.image.tag = "${{ env.APP_VERSION }}"' values.yaml
            yq -i '.spring-base.ingress.host = "${{ env.HOST }}"' values.yaml

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update Image tag to ${{ env.APP_VERSION }}
