name: Build, Push, Deploy (Dev)

on:
  push:
    branches:
      - main
      - ci
  workflow_dispatch:

env:
  IMAGE_REPOSITORY: ${{ vars.REGISTRY }}/${{ vars.ORGANIZATION }}/${{ github.event.repository.name }}
  # APP_VERSION: ${{ github.sha }}
  APP_VERSION: test # TODO: change env
  HOST: dev.${{ vars.HOST }}

jobs:
  build-and-push:
    if: false # TODO: delete line
    environment: dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build jar with Gradle
        uses: IsItgone/ci-templates/.github/actions/build-jar@main

      - name: Build and Push image with Docker buildx
        uses: IsItgone/ci-templates/.github/actions/build-and-push-image@main
        with:
          registry: ${{ vars.REGISTRY }}
          tags: |
            ${{ env.IMAGE_REPOSITORY }}:${{ env.APP_VERSION }}
          password: ${{ secrets.GHCR_TOKEN }}

  update-helm-chart:
    #    needs: build-and-push # TODO: uncomment
    permissions:
      contents: write
    environment: dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: charts

      - name: Update Helm Chart
        uses: mikefarah/yq@v4
        with:
          cmd: |
            yq -i '.appVersion = "${{ env.APP_VERSION }}"' chart/Chart.yaml
            yq -i '.image.repository = "${{ env.IMAGE_REPOSITORY }}"' chart/values.yaml
            yq -i '.ingress.host = "${{ env.HOST }}"' chart/dev-values.yaml

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update App version to ${{ env.APP_VERSION }}
