name: Build and Push Package (Dev)

on:
  push:
    branches:
      - main
      - ci
  workflow_dispatch:

env:
  IMAGE_REPOSITORY: ${{ vars.REGISTRY }}/${{ vars.ORGANIZATION }}/${{ github.event.repository.name }}
  COMMIT_HASH: ${{ github.sha }}

jobs:
  build-and-push:
    environment: dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build jar with Gradle
        uses: IsItgone/ci-templates/.github/actions/build-jar@main

      - name: Build and Push image with Docker buildx
        uses: IsItgone/ci-templates/.github/actions/build-and-push-image@main
        with:
          registry: ${{ vars.REGISTRY }}
          tags: |
            ${{ env.IMAGE_REPOSITORY }}:${{ env.COMMIT_HASH }}
          password: ${{ secrets.GHCR_TOKEN }}
