name: Deploy to Prod Environment

on:
  release:
    types: [ published ]

jobs:
  build-and-deploy:
    environment: prod
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: refs/tags/${{ github.event.release.tag_name }}

      - name: Build jar with Gradle
        uses: IsItgone/ci-templates/.github/actions/build-jar@main

      - name: Build image with Docker buildx
        uses: IsItgone/ci-templates/.github/actions/build-and-push-image@main
        with:
          tags: ${{ vars.ORG_NAME }}/${{ github.event.repository.name }}:${{ github.event.release.tag_name }},${{ vars.ORG_NAME }}/${{ github.event.repository.name }}:latest
          password: ${{ secrets.GHCR_TOKEN }}
